### ISSUE TITLE
Update the README/package description

### ISSUE THREAD

**Issue by jamartis** [aufover/ldpwrap#4]

**Comment by kdudka** [comment]
@jamartis Any update on this?  What about the following summary?
```
A shared library that can be preloaded to instrument the main() function of programs being executed
```

**Comment by jamartis** [comment]
Thanks @kdudka. Should be fixed by https://github.com/aufover/ldpwrap/commit/9a4910f6f812af6a3740ac80f386c67b331ba1ab
